[package]
name = "do"
version = "0.1.1"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "GPL-2.0"
description = "Do is a Microsoft To Do client for Linux built with Rust and GTK."
homepage = "https://do.edfloreshz.dev/"
documentation = "https://docs.rs/do"
repository = "https://github.com/edfloreshz/do/"
readme = "README.md"

[dependencies]
gtk4 = "0.4.6"
glib = "0.15.10"
libadwaita = "0.1.1"
relm4-macros = "0.4.3"
cascade = "1.0.0"
reqwest = { version = "0.11.10", features = ["blocking", "json"]}
tokio = { version = "1.17.0", features = ["full"]}
libdmd = "0.1.6"
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0"
anyhow = "1.0.56"
chrono = { version = "0.4.19", features = ["serde"] }
async-trait = "0.1.53"
open = "2.1.1"
image = "0.24.1"
dirs = "4.0.0"